
import React, { useState, useEffect } from 'react';
import { useAuth, UserRole } from '../contexts/AuthContext';
import { User } from '../types';
import Input from '../components/ui/Input';
import Select from '../components/ui/Select';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';
import Alert from '../components/ui/Alert';

const UserRow: React.FC<{user: User, onRoleChange: (userId: string, role: UserRole) => void}> = ({ user, onRoleChange }) => {
  const [selectedRole, setSelectedRole] = useState<UserRole>(user.role);
  const {currentUser} = useAuth();

  const handleSelectChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setSelectedRole(e.target.value as UserRole);
  };

  const handleUpdateRole = () => {
    onRoleChange(user.id, selectedRole);
  };
  
  const isCurrentUser = currentUser?.id === user.id;

  return (
    <tr className="border-b border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors">
      <td className="py-3 px-4 text-sm text-slate-700 dark:text-slate-300">{user.username}</td>
      <td className="py-3 px-4 text-sm">
        <Select
          value={selectedRole}
          onChange={handleSelectChange}
          options={Object.values(UserRole).map(role => ({ value: role, label: role.charAt(0).toUpperCase() + role.slice(1) }))}
          className="text-sm dark:bg-slate-700"
          wrapperClassName="mb-0"
          disabled={isCurrentUser} // Prevent admin from changing their own role easily here
        />
      </td>
      <td className="py-3 px-4 text-sm">
        <Button onClick={handleUpdateRole} size="sm" variant="secondary" disabled={selectedRole === user.role || isCurrentUser}>
          Update Role
        </Button>
      </td>
    </tr>
  );
};


const HumanResourcePage: React.FC = () => {
  const { users, addUser, updateUserRole } = useAuth();
  const [newUser, setNewUser] = useState({ username: '', password: '', role: UserRole.CREATIVE });
  const [notification, setNotification] = useState<{ type: 'success' | 'error', message: string } | null>(null);
  const [clientUsers, setClientUsers] = useState<User[]>([]);

  useEffect(() => {
    setClientUsers(users);
  }, [users]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setNewUser({ ...newUser, [e.target.name]: e.target.value });
  };

  const handleAddUser = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newUser.username || !newUser.password) {
      setNotification({ type: 'error', message: 'Username and password are required.' });
      return;
    }
    try {
      await addUser({ id: '', ...newUser }); // ID will be generated by AuthContext
      setNotification({ type: 'success', message: `User ${newUser.username} added successfully.` });
      setNewUser({ username: '', password: '', role: UserRole.CREATIVE }); // Reset form
    } catch (error: any) {
      setNotification({ type: 'error', message: error.message || 'Failed to add user.' });
    }
    setTimeout(() => setNotification(null), 3000);
  };

  const handleRoleChange = async (userId: string, role: UserRole) => {
     try {
      await updateUserRole(userId, role);
      setNotification({ type: 'success', message: `User role updated successfully.` });
    } catch (error: any) {
      setNotification({ type: 'error', message: error.message || 'Failed to update user role.' });
    }
    setTimeout(() => setNotification(null), 3000);
  };


  return (
    <div className="container mx-auto">
      <h1 className="text-3xl font-bold mb-6 text-slate-800 dark:text-slate-100">Human Resources</h1>
      {notification && <Alert type={notification.type} message={notification.message} onClose={() => setNotification(null)} />}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1">
          <Card title="Add New User">
            <form onSubmit={handleAddUser} className="space-y-4">
              <Input
                label="Username"
                id="username"
                name="username"
                type="text"
                value={newUser.username}
                onChange={handleInputChange}
                required
              />
              <Input
                label="Password"
                id="password"
                name="password"
                type="password"
                value={newUser.password}
                onChange={handleInputChange}
                required
              />
              <Select
                label="Role"
                id="role"
                name="role"
                value={newUser.role}
                onChange={handleInputChange}
                options={Object.values(UserRole).map(role => ({ value: role, label: role.charAt(0).toUpperCase() + role.slice(1) }))}
              />
              <Button type="submit" variant="primary" className="w-full">Add User</Button>
            </form>
          </Card>
        </div>

        <div className="lg:col-span-2">
          <Card title="Manage Users">
            {clientUsers.length > 0 ? (
              <div className="overflow-x-auto">
                <table className="w-full min-w-max">
                  <thead className="bg-slate-100 dark:bg-slate-700">
                    <tr>
                      <th className="py-3 px-4 text-left text-xs font-medium text-slate-500 dark:text-slate-300 uppercase tracking-wider">Username</th>
                      <th className="py-3 px-4 text-left text-xs font-medium text-slate-500 dark:text-slate-300 uppercase tracking-wider">Role</th>
                      <th className="py-3 px-4 text-left text-xs font-medium text-slate-500 dark:text-slate-300 uppercase tracking-wider">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200 dark:divide-slate-700">
                    {clientUsers.map(user => (
                      <UserRow key={user.id} user={user} onRoleChange={handleRoleChange} />
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <p className="text-center text-slate-500 dark:text-slate-400">No users found.</p>
            )}
          </Card>
        </div>
      </div>
    </div>
  );
};

export default HumanResourcePage;
