
import React from 'react';
import Card from '../components/ui/Card';
import { APP_NAME } from '../constants';

const PrivacyPolicyPage: React.FC = () => {
  return (
    <div className="container mx-auto py-8 px-4">
      <Card title="Privacy Policy" className="max-w-4xl mx-auto">
        <div className="space-y-4 text-slate-700 dark:text-slate-300">
          <p className="text-sm">Last updated: {new Date().toLocaleDateString()}</p>
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. Given that {APP_NAME} primarily stores data locally in your browser, "collection" and "use" mostly pertain to data handling within your browser environment.</p>

          <h2 className="text-xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-100">Interpretation and Definitions</h2>
          <h3 className="text-lg font-semibold mt-4 mb-1 text-slate-800 dark:text-slate-100">Interpretation</h3>
          <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          <h3 className="text-lg font-semibold mt-4 mb-1 text-slate-800 dark:text-slate-100">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className="list-disc list-inside space-y-1">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to {APP_NAME}.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. This application primarily uses localStorage and sessionStorage, not traditional server-set cookies for core functionality.</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. In the context of {APP_NAME}, this includes data You input and is stored in Your browser's local storage.</li>
            <li><strong>Service</strong> refers to the Application.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). For {APP_NAME}, this would be limited to client-side interactions.</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 className="text-xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-100">Collecting and Using Your Personal Data</h2>
          <h3 className="text-lg font-semibold mt-4 mb-1 text-slate-800 dark:text-slate-100">Types of Data Collected</h3>
          <h4 className="text-md font-semibold mt-3 mb-1 text-slate-800 dark:text-slate-100">Personal Data</h4>
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Since data is stored locally, "asking You to provide" means information You input into the application which is then stored in Your browser's local storage. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>Username (for account identification within the app)</li>
            <li>Profile picture (stored as a base64 string locally)</li>
            <li>Content You generate (e.g., social media posts, prompts)</li>
            <li>Usage Data (client-side interactions, e.g., theme preference)</li>
          </ul>
          <h4 className="text-md font-semibold mt-3 mb-1 text-slate-800 dark:text-slate-100">Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service (client-side).</p>
          <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address - though not actively collected or transmitted by this app), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. All this primarily occurs and is contained within your browser's environment for {APP_NAME}.</p>
          
          <h2 className="text-xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-100">Use of Your Personal Data</h2>
          <p>{APP_NAME} may use Personal Data (stored and processed locally in your browser) for the following purposes:</p>
          <ul className="list-disc list-inside space-y-1">
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service (client-side monitoring).</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
            <li><strong>To personalize your experience:</strong> such as remembering your theme preference or auto-login information.</li>
            <li><strong>To enable AI functionalities:</strong> The WebLLM model runs locally in your browser, processing your inputs to generate content. If configured to use external APIs like Gemini, data would be sent to Google according to their policies.</li>
          </ul>

          <h2 className="text-xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-100">Retention of Your Personal Data</h2>
          <p>The Company (referring to the application logic running in your browser) will retain Your Personal Data only for as long as it is stored in Your browser's local storage. You have control over clearing your browser's storage, which would remove this data.</p>
          
          <h2 className="text-xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-100">Disclosure of Your Personal Data</h2>
          <p>As a client-side application that stores data locally, {APP_NAME} does not "disclose" Your Personal Data to external third parties by default. If you use features that integrate with third-party services (like a potential future social media API integration, or cloud AI services), data sharing would be subject to those services' policies and your consent.</p>


          <h2 className="text-xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-100">Security of Your Personal Data</h2>
          <p>The security of Your Personal Data is important to Us. All user data, including user credentials (if applicable for local storage access) and content, is stored locally in your browser's localStorage. While this offers a degree of privacy by not transmitting data to external servers by default, the security of localStorage is dependent on your browser's security and your device's overall security. Be aware of the risks associated with browser storage if your device is compromised. AI model processing with WebLLM also occurs locally in your browser.</p>

          <h2 className="text-xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-100">Children's Privacy</h2>
          <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13 through our local storage mechanisms. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data (i.e., used the app and stored data locally), please guide them on managing browser data. If We become aware that We have inadvertently facilitated local storage of Personal Data from anyone under the age of 13 without verification of parental consent, We would advise on steps to clear such local data.</p>

          <h2 className="text-xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-100">Links to Other Websites</h2>
          <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
          <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

          <h2 className="text-xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-100">Changes to this Privacy Policy</h2>
          <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

          <h2 className="text-xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-100">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>By email: contact@example.com (Replace with actual contact)</li>
             <li>By visiting this page on our website: [Link to Contact Page if exists]</li>
          </ul>
        </div>
      </Card>
    </div>
  );
};
export default PrivacyPolicyPage;
